name: idea_maker
description: "アイデア創出サポートアプリ"

version: 0.0.0

environment:
  sdk: 3.8.1

dependencies:
  collection: 1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_svg: 2.2.0
  freezed_annotation: 3.1.0
  go_router: 16.0.0
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  logger: 2.6.0
  riverpod_annotation: 2.6.1
  uuid: 4.5.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_gen_runner: 5.11.0
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  go_router_builder: 3.0.1
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5
  very_good_analysis: 9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - ./lib/assets/icons/

flutter_gen:
  integrations:
    flutter_svg: true
