name: idea_maker
description: "アイデア創出サポートアプリ"

version: 0.0.0

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 15.2.4
  intl: 0.20.2
  hooks_riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  flutter_hooks: 0.21.2
  riverpod_annotation: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5
  go_router_builder: 3.0.1
  build_runner: 2.4.15

flutter:
  uses-material-design: true
  generate: true
