name: ideamaker
description: "アイデア創出サポートアプリ"

version: 0.0.0

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 15.2.4
  intl: 0.20.2
  riverpod: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  generate: true
