name: idea_maker
description: "アイデア創出サポートアプリ"

version: 0.0.0

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  go_router: 15.2.4
  hooks_riverpod: 2.6.1
  intl: 0.20.2
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: 3.0.1
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5
  very_good_analysis: 9.0.0

flutter:
  uses-material-design: true
  generate: true
